### ISSUE TITLE
Preview on a linux version

### ISSUE THREAD

**Issue by me-vlad** [rse/vingester#36]
Vingester 2.2.5 for linux
OS: Fedora 34 x86_64, kernel 5.12.9-300, GPU Nvidia GeForce GT 755M, Gnome 40.1.0, Wayland 1.19.0, nouveau 1.0.17

While running frameless output with preview enabled - preview shows nothing on a linux Vingester version.
Same source with same settings on Windows version - works fine.
Screenshot:

![image](https://user-images.githubusercontent.com/222185/121431312-e8e1ac00-c981-11eb-94cc-8bda8bdc9ca4.png)

**Comment by rse** [comment]
That's strange: I tested it once under Ubuntu with exactly the same broken preview as in your screenshot. I then enabled "Headless" mode and disabled "frameless" mode. For "headless" mode I've seen that my "Sample Rate" was not set, so I set it and I got a preview afterwards, too. Now the strange thing: I now switched back to "frameless" mode and it works now. Can it be that also for you in the fields of "headless" mode there are some problems? Can you show me the entire config or just export it and append it here?

**Comment by me-vlad** [comment]
Sure, exported config

``` yaml
%YAML 1.2
##
##  Vingester Configuration
##  Version: Vingester 2.2.5
##  Date:    2021-06-10 00:56
##

---

-   BrowserTitle:                  "The-Expert-4"
    BrowserInfo:                   "The Expert: IT Support (Square Project Episode 2)"
    BrowserWidth:                  854
    BrowserHeight:                 480
    BrowserColor:                  "transparent"
    BrowserZoom:                   1
    BrowserTrust:                  false
    BrowserNodeAPI:                false
    BrowserOBSDOM:                 false
    BrowserPersist:                false
    InputURL:                      "https://www.youtube.com/embed/ZOzzRlc_qho?autoplay=1&controls=0&rel=0"
    PatchDelay:                    0
    PatchFrame:                    ""
    PatchStyleType:                "inline"
    PatchStyleCode:                ""
    PatchScriptType:               "inline"
    PatchScriptCode:               ""
    Output1Enabled:                true
    Output1VideoPositionX:         0
    Output1VideoPositionY:         0
    Output1VideoDisplay:           1
    Output1VideoPinTop:            false
    Output1AudioDevice:            ""
    Output2Enabled:                false
    Output2VideoFrameRate:         30
    Output2VideoAdaptive:          false
    Output2VideoDelay:             0
    Output2AudioSampleRate:        48000
    Output2AudioChannels:          2
    Output2AudioDelay:             0
    Output2SinkNDIEnabled:         false
    Output2SinkFFmpegEnabled:      true
    Output2SinkFFmpegMode:         "cbr"
    Output2SinkFFmpegFormat:       "mpegts"
    Output2SinkFFmpegOptions:      "srt://127.0.0.1:10000?&pkt_size=1316&mode=caller"
    PreviewEnabled:                true
    ConsoleEnabled:                true
    DevToolsEnabled:               false
    Collapsed:                     false
```
