### ISSUE TITLE
Headless NDI output resolution

### ISSUE THREAD

**Issue by me-vlad** [rse/vingester#39]
Headless NDI output creates a NDI stream with wrong resolution when frameless output is disabled (please see screenshots with a Vingester main window and NDI monitor).
When frameless output is enabled  - NDI output resolution is OK.
Vingester version: 2.2.6
OS: Windows 10 Pro x86_64 21H1

![image](https://user-images.githubusercontent.com/222185/122678057-c0fa1000-d1ed-11eb-8919-50e572e4af61.png)

![image](https://user-images.githubusercontent.com/222185/122678067-cbb4a500-d1ed-11eb-855f-8c3fa5647bca.png)

**Comment by rse** [comment]
I've tried exactly your test under both macOS and Windows and it worked as expected:

**Comment by me-vlad** [comment]
Can you try to change your monitor resolution to 1920x1080?
When I set Vingester output size to 1280x720 on a fullhd notebook NDI stream resolution is 1280x720, but when I set output to 1080p - NDI resolution is 1482x834

**Comment by rse** [comment]
I've tried it on a 1920x1080 pixel display. But it made no difference: it worked as expected:

![image](https://user-images.githubusercontent.com/221273/122682847-189f7800-d1fc-11eb-8284-ee89756bca6d.png)

**Comment by rse** [comment]
Can you export your exact configuration and show me the YAML file, please? Perhaps there is something still different between our configurations...

**Comment by me-vlad** [comment]
> Can you export your exact configuration and show me the YAML file, please? Perhaps there is something still different between our configurations...


``` yaml
%YAML 1.2
##
##  Vingester Configuration
##  Version: Vingester 2.2.6
##  Date:    2021-06-20 20:24
##

---

-   BrowserTitle:                  "Vingester-Test"
    BrowserInfo:                   "Vingester Test Page"
    BrowserWidth:                  1920
    BrowserHeight:                 1080
    BrowserColor:                  "transparent"
    BrowserZoom:                   1
    BrowserTrust:                  false
    BrowserNodeAPI:                false
    BrowserOBSDOM:                 false
    BrowserPersist:                false
    InputURL:                      "https://vingester.app/test/"
    PatchDelay:                    0
    PatchFrame:                    ""
    PatchStyleType:                "inline"
    PatchStyleCode:                ""
    PatchScriptType:               "inline"
    PatchScriptCode:               ""
    Output1Enabled:                false
    Output1VideoPositionX:         0
    Output1VideoPositionY:         0
    Output1VideoDisplay:           0
    Output1VideoPinTop:            false
    Output1AudioDevice:            ""
    Output2Enabled:                true
    Output2VideoFrameRate:         30
    Output2VideoAdaptive:          false
    Output2VideoDelay:             0
    Output2AudioSampleRate:        48000
    Output2AudioChannels:          2
    Output2AudioDelay:             0
    Output2SinkNDIEnabled:         true
    Output2SinkFFmpegEnabled:      false
    Output2SinkFFmpegMode:         "vbr"
    Output2SinkFFmpegFormat:       "matroska"
    Output2SinkFFmpegOptions:      "vingester-test.mkv"
    PreviewEnabled:                false
    ConsoleEnabled:                false
    DevToolsEnabled:               false
    Collapsed:                     false
```
