### ISSUE TITLE
Vingester instance with custom profile duplicates browser outputs on global START

### ISSUE THREAD

**Issue by me-vlad** [rse/vingester#41]
Tested on Win 10 , Vingester 2.2.6 and 2.2.9

Vingester with custom profile started from shortcut running comand like
C:\Users\Vlad\Desktop\Vingester.exe --tag=TEST --profile=C:\WORK\TEST --config=C:\WORK\TEST\scenes.yaml 

After click on GLOBAL START button all browser outputs started twice.
You can see this issue on a [screencast](https://drive.google.com/file/d/1j3sA173HG04OkAkgVM7ZZJe_bekNWKMH/view)

Vingecter with common profile started directly from exe file - works as expected.

Config imported from file

``` yaml
%YAML 1.2
##
##  Vingester Configuration
##  Version: Vingester 2.2.6
##  Date:    2021-06-27 18:35
##

---

-   BrowserTitle:                  "The-Expert-1"
    BrowserInfo:                   "The Expert: 7 Red Lines (Original Sketch)"
    BrowserWidth:                  864
    BrowserHeight:                 480
    BrowserColor:                  "transparent"
    BrowserZoom:                   1
    BrowserTrust:                  false
    BrowserNodeAPI:                false
    BrowserOBSDOM:                 false
    BrowserPersist:                false
    InputURL:                      "https://www.youtube.com/embed/BKorP55Aqvg?autoplay=1&controls=0&rel=0"
    PatchDelay:                    0
    PatchFrame:                    ""
    PatchStyleType:                "inline"
    PatchStyleCode:                ""
    PatchScriptType:               "inline"
    PatchScriptCode:               ""
    Output1Enabled:                true
    Output1VideoPositionX:         0
    Output1VideoPositionY:         0
    Output1VideoDisplay:           1
    Output1VideoPinTop:            false
    Output1AudioDevice:            ""
    Output2Enabled:                false
    Output2VideoFrameRate:         24
    Output2VideoAdaptive:          false
    Output2VideoDelay:             0
    Output2AudioSampleRate:        48000
    Output2AudioChannels:          2
    Output2AudioDelay:             0
    Output2SinkNDIEnabled:         true
    Output2SinkFFmpegEnabled:      false
    Output2SinkFFmpegMode:         "vbr"
    Output2SinkFFmpegFormat:       "matroska"
    Output2SinkFFmpegOptions:      "the-expert-1.mkv"
    PreviewEnabled:                false
    ConsoleEnabled:                false
    DevToolsEnabled:               false
    Collapsed:                     false

-   BrowserTitle:                  "The-Expert-3"
    BrowserInfo:                   "The Expert: Wrong Angle (Square Project Episode 1)"
    BrowserWidth:                  854
    BrowserHeight:                 480
    BrowserColor:                  "transparent"
    BrowserZoom:                   1
    BrowserTrust:                  false
    BrowserNodeAPI:                false
    BrowserOBSDOM:                 false
    BrowserPersist:                false
    InputURL:                      "https://www.youtube.com/embed/mokllJ_Sz_g?autoplay=1&controls=0&rel=0"
    PatchDelay:                    0
    PatchFrame:                    ""
    PatchStyleType:                "inline"
    PatchStyleCode:                ""
    PatchScriptType:               "inline"
    PatchScriptCode:               ""
    Output1Enabled:                true
    Output1VideoPositionX:         855
    Output1VideoPositionY:         0
    Output1VideoDisplay:           1
    Output1VideoPinTop:            false
    Output1AudioDevice:            ""
    Output2Enabled:                false
    Output2VideoFrameRate:         24
    Output2VideoAdaptive:          false
    Output2VideoDelay:             0
    Output2AudioSampleRate:        48000
    Output2AudioChannels:          2
    Output2AudioDelay:             0
    Output2SinkNDIEnabled:         true
    Output2SinkFFmpegEnabled:      false
    Output2SinkFFmpegMode:         "vbr"
    Output2SinkFFmpegFormat:       "matroska"
    Output2SinkFFmpegOptions:      "the-expert-3.mkv"
    PreviewEnabled:                false
    ConsoleEnabled:                false
    DevToolsEnabled:               false
    Collapsed:                     false
```
